import { and, asc, eq, gte, isNotNull, isNull, lte, sql } from 'drizzle-orm';
import { db } from '@/db/client';
import { events, type Event, type Recurrence } from '@/db/schema';
import { newId } from '@/lib/id';
import { verifyPriorityOwnership } from '@/lib/priority-ownership';
import {
  type DisplayedEvent,
  materializeVirtualEvent,
  recurrenceIncludesDate,
} from '@/lib/recurrence';

export type CreateEventInput = {
  ownerPriorityId: string;
  title: string;
  description?: string | null;
  startTime: Date;
  endTime: Date;
  recurrence?: Recurrence | null;
};

export type UpdateEventPatch = {
  title?: string;
  description?: string | null;
  startTime?: Date;
  endTime?: Date;
  recurrence?: Recurrence | null;
  completionStatus?: 'attended' | 'missed' | null;
};

export async function getEventsForPriority(
  userId: string,
  priorityId: string,
): Promise<Event[]> {
  return db
    .select()
    .from(events)
    .where(
      and(
        eq(events.userId, userId),
        eq(events.ownerPriorityId, priorityId),
        isNull(events.deletedAt),
      ),
    )
    .orderBy(asc(events.startTime));
}

export async function getEventById(userId: string, eventId: string): Promise<Event | null> {
  const rows = await db
    .select()
    .from(events)
    .where(and(eq(events.id, eventId), eq(events.userId, userId), isNull(events.deletedAt)))
    .limit(1);
  return rows[0] ?? null;
}

/**
 * Returns the user's events whose start_time falls within [startISO, endISO]
 * (inclusive), plus virtual instances of recurring templates whose pattern
 * includes any date in that range. See TDD §937-970 (events analog).
 *
 * Range is interpreted as UTC date-only bounds: startISO 00:00 UTC through
 * endISO 23:59:59.999 UTC. Callers in user-TZ contexts should compute the
 * range in their TZ and then pass UTC equivalents.
 */
export async function getEventsForDateRange(
  userId: string,
  startISO: string,
  endISO: string,
): Promise<DisplayedEvent[]> {
  const startUtc = new Date(`${startISO}T00:00:00.000Z`);
  const endUtc = new Date(`${endISO}T23:59:59.999Z`);

  const realRows = await db
    .select()
    .from(events)
    .where(
      and(
        eq(events.userId, userId),
        gte(events.startTime, startUtc),
        lte(events.startTime, endUtc),
        isNull(events.deletedAt),
      ),
    );

  const templates = await db
    .select()
    .from(events)
    .where(
      and(
        eq(events.userId, userId),
        isNotNull(events.recurrence),
        isNull(events.instanceOfEventId),
        isNull(events.deletedAt),
      ),
    );

  // Override coverage: real overrides whose start_time falls on a date already
  // generated by their template should suppress the virtual one.
  const coveredTemplates = new Set(
    realRows
      .filter((e) => e.instanceOfEventId !== null)
      .map((e) => `${e.instanceOfEventId}:${e.startTime.toISOString().slice(0, 10)}`),
  );

  const virtuals: DisplayedEvent[] = [];
  // Walk each date in the range; compact loop since v1 ranges are small (1-7 days for a week view).
  for (let cursor = new Date(startUtc); cursor <= endUtc; cursor = new Date(cursor.getTime() + 86_400_000)) {
    const dateISO = cursor.toISOString().slice(0, 10);
    for (const template of templates) {
      if (!template.recurrence) continue;
      const templateStartISO = template.startTime.toISOString().slice(0, 10);
      if (!recurrenceIncludesDate(template.recurrence, templateStartISO, dateISO)) continue;
      if (coveredTemplates.has(`${template.id}:${dateISO}`)) continue;
      virtuals.push(materializeVirtualEvent(template, dateISO));
    }
  }

  const reals: DisplayedEvent[] = realRows.map((e) => ({ ...e, kind: 'real' }));
  return [...reals, ...virtuals].sort(
    (a, b) => a.startTime.getTime() - b.startTime.getTime(),
  );
}

export async function createEvent(
  userId: string,
  input: CreateEventInput,
): Promise<Event | null> {
  const ok = await verifyPriorityOwnership(userId, input.ownerPriorityId);
  if (!ok) return null;

  const [row] = await db
    .insert(events)
    .values({
      id: newId('evt'),
      ownerPriorityId: input.ownerPriorityId,
      userId,
      title: input.title,
      description: input.description ?? null,
      startTime: input.startTime,
      endTime: input.endTime,
      recurrence: input.recurrence ?? null,
    })
    .returning();
  return row ?? null;
}

export async function updateEvent(
  userId: string,
  eventId: string,
  patch: UpdateEventPatch,
): Promise<Event | null> {
  const set: Record<string, unknown> = { updatedAt: new Date() };
  for (const [key, value] of Object.entries(patch)) {
    if (value !== undefined) set[key] = value;
  }
  if (patch.completionStatus !== undefined) {
    set.completedAt = patch.completionStatus === null ? null : new Date();
  }
  if (Object.keys(set).length === 1) return getEventById(userId, eventId);

  const [row] = await db
    .update(events)
    .set(set)
    .where(and(eq(events.id, eventId), eq(events.userId, userId), isNull(events.deletedAt)))
    .returning();
  return row ?? null;
}

export async function softDeleteEvent(userId: string, eventId: string): Promise<boolean> {
  const now = new Date();
  const updated = await db
    .update(events)
    .set({ deletedAt: now, updatedAt: now })
    .where(and(eq(events.id, eventId), eq(events.userId, userId), isNull(events.deletedAt)))
    .returning({
      id: events.id,
      recurrence: events.recurrence,
      instanceOf: events.instanceOfEventId,
    });
  if (updated.length === 0) return false;

  const head = updated[0];
  if (head && head.recurrence !== null && head.instanceOf === null) {
    await db
      .update(events)
      .set({ deletedAt: now, updatedAt: now })
      .where(and(eq(events.instanceOfEventId, eventId), isNull(events.deletedAt)));
  }
  return true;
}

/** M9-targeted helper for materializing an event override row. */
export async function materializeEventOverride(
  userId: string,
  templateId: string,
  startTime: Date,
  endTime: Date,
  patch: Omit<UpdateEventPatch, 'recurrence'> = {},
): Promise<Event | null> {
  const template = await getEventById(userId, templateId);
  if (!template || template.recurrence === null) return null;

  const [row] = await db
    .insert(events)
    .values({
      id: newId('evt'),
      ownerPriorityId: template.ownerPriorityId,
      userId,
      title: patch.title ?? template.title,
      description: patch.description ?? template.description,
      startTime,
      endTime,
      recurrence: null,
      instanceOfEventId: templateId,
      completionStatus: patch.completionStatus ?? null,
      completedAt: patch.completionStatus ? new Date() : null,
    })
    .returning();
  return row ?? null;
}

/**
 * Used by softDeletePriority. Soft-deletes all of a Priority's events except
 * those with completion_status set AND end_time in the past (TDD §472-512).
 */
export async function cascadeSoftDeleteEventsForPriority(
  ownerPriorityId: string,
  now: Date,
): Promise<void> {
  await db.execute(sql`
    UPDATE events SET deleted_at = ${now}, updated_at = ${now}
    WHERE owner_priority_id = ${ownerPriorityId}
      AND deleted_at IS NULL
      AND NOT (
        completed_at IS NOT NULL
        AND end_time < ${now}
      )
  `);
}
